// USER AUTH
export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_ADMIN = 'SET_ADMIN'

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUET'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

// SIGN UP
export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST'
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE'

export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO'
export const RECEIVE_USER_FAILURE = 'RECEIVE_USER_FAILURE'
export const RECEIVE_USER_SUCCESS = 'RECEIVE_USER_SUCCESS'

export const SET_ACCESS_LEVEL = 'SET_ACCESS_LEVEL'
export const SET_MONGO_ID = 'SET_MONGO_ID'

